### ISSUE TITLE
Could you suggest a way to integrate this with react-redux?

### ISSUE THREAD

**Issue by Amandeepsinghghai** [musterknabe/translate.js#8]
I am working on a a project that has the requirement of localization and was wondering if this library has been integrated with react/react-redux or flux? 
Any help would be greatly appreciated.

**Comment by StephanHoyer** [comment]
I haven't used react with translate.js yet. But since i18n is a view problem, it might not touch redux/flux-stores.

I think integration would be probably the same as https://github.com/i18next/react-i18next. JSX is not so well suited for i18n.

That's why we don't use react, but mithril.js. It's just simple JS all the way down. Much simpler to integrate.
